DATASETS:
  SOURCE: [GTA5,]
  TARGET: [Cityscapes,]
  NUM_CLASSES: 19
DATALOADER:
  BATCH_SIZE_SOURCE: 4
  BATCH_SIZE_TARGET: 4
INPUT:
  INPUT_SIZE_SOURCE: [1024, 512]
  INPUT_SIZE_TARGET: [1024, 512]
MODEL:
  MODEL: DeepLabv2
  MULTI_LEVEL: True
  RESTORE_FROM: ../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
DA:
  DA_TYPE: DA
  DA_METHOD: Baseline
  BRIDGE_TYPE: class
  DOMAIN_LABEL: True
TRAIN:
  EARLY_STOP: 60000
TEST:
  INPUT_SIZE: [1024, 512]
